name: Metrics
on:
  # Schedule daily updates
  schedule:
    [{ cron: "0 0 * * *" }]
    # (Opcional) Permite ejecutar manualmente la acción
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 6
          token: ${{secrets.METRICS_TOKEN}}
